services:
  - type: web
    name: chat-bot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cpu
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18  # Using Python 3.9 for better compatibility
      - key: PORT
        value: 10000
    plan: free
