services:
  - type: web
    name: chat-bot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 --index-url https://download.pytorch.org/whl/cpu
      pip install --no-cache-dir -r requirements.txt
    startCommand: python -m uvicorn main:app --host=0.0.0.0 --port=$PORT --workers=1
    envVars:
      - key: PORT
        value: 10000
      - key: PIP_DEFAULT_TIMEOUT
        value: "100"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PYTHON_VERSION
        value: "3.9.18"
    plan: free
