services:
  - type: web
    name: chat-bot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13  # Explicitly using Python 3.10 for PyTorch compatibility
      - key: PORT
        value: 10000
    plan: free
